### PR TITLE
Allow style transfer to images of different dimensions

### PR DESCRIPTION
**Pull request by cbonitz**
Allow multiple input images of different dimensions:
First inspect all images to group them by shape, then run one TF session for each distinct shape.

Two thoughts regarding performance:
* We're loading images twice: Once to get their size, and once during processing. This requires extra I/O and processing but avoids running out of memory for large folders.
* We're running multiple TF sessions. There is no technical alternative to this because of input dimensions, so this is the price of improved usability due to being able to use images of different size.

### CODE REVIEW

**Comment by cbonitz** [comment]
This solves issue #12 (a feature request of mine).

**Comment by cbonitz** [comment]
Cleaned up a bit (amended to the original commit):
* Removed print statement that I added for debugging
* Roll back whitespace change
* Use parens with print call
* Use single quotes for strings

**Comment by lengstrom** [comment]
Let me know when this is ready to review!

**Comment by cbonitz** [comment]
Now it is :)

**Comment by cbonitz** [comment]
Did you find time to review this yet? Any issues with the code?

**Comment by lengstrom** [comment]
This looks great! Could you make sure that every line is <= 80 characters long, and also add documentation for the option you added in `docs.md`?

**Comment by cbonitz** [comment]
Thanks for the feedback. I added documentation and wrapped lined that were too long (both in new and existing code of `evaluete.py`).

**Comment by lengstrom** [comment]
Looks good!

**Pull request merged**
