### PR TITLE
Use moviepy to transform video.

### PR DESCRIPTION
**Pull request by AndyZhu1991**
Avoid create temp image files.
Audio transform support.

### CODE REVIEW

**Comment by Schwusch** [comment]
Nicely done! Looks a lot cleaner

**Comment by AndyZhu1991** [comment]
@Schwusch 
Thanks!
And I have tested it on python3.5, not python2.7, FYI.

**Comment by zoidburg** [comment]
@AndyZhu1991 
Hi, nice work~ 
There's something wrong when I use transfrom_video.py, the scene in the output video keeps *shifting up side down*. So any ideas on this?
thanks
ps: this is the **input** video
metro
and this is the **output** video
video

**Comment by AndyZhu1991** [comment]
@zoidburg 
Can you send the video file to me?
It works fine with my test video.

**Comment by zoidburg** [comment]
@AndyZhu1991 
of course, the video is in the following link, and I'll try testing on other video too.

link: http://pan.baidu.com/s/1hr6uHla
code: kyu4

**Comment by diwu1989** [comment]
I tried out this patch on some drone video and it worked fine for me, no video decoding error. The problem that's seen with the video shifting is probably due to some encoding issue on the source material as it is not reproducible on my source video.

**Comment by lengstrom** [comment]
Sweet, thanks!

**Pull request merged**
